apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- api-gateway-deployment.yaml
- api-gateway-service.yaml
- rabbitmq-statefulset.yaml
- rabbitmq-service.yaml

namespace: ecommerce

images:
- name: api-gateway
  newName: ghcr.io/your-repo/api-gateway
  newTag: latest

commonLabels:
  app.kubernetes.io/part-of: ecommerce
  app.kubernetes.io/managed-by: kustomize