apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-mongodb
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-mongodb
  template:
    metadata:
      labels:
        app: payments-mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:6
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: payments-mongodb-data
          mountPath: /data/db
      volumes:
      - name: payments-mongodb-data
        persistentVolumeClaim:
          claimName: payments-mongodb-pvc